# Generated by Django 3.0.5 on 2020-05-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20200505_2050'),
        ('ecom', '0009_remove_transaction_amounts'),
    ]

    operations = [
    ]
